### ISSUE TITLE
Different style and/or color for each tag

### ISSUE THREAD

**Issue by cmorillas** [lekoala/bootstrap5-tags#10]
Congratulations for this snippet. 
I wonder if it can be posible to have different color and/or style per tag.
May be with an attribute in each `<option>`. For example:
`<option value="1" data-badge-style="secondary">First</option>`
`<option value="2" data-badge-style="primary">Second</option>`

Thank you for your work !!

**Comment by lekoala** [comment]
@cmorillas that seems easy enough, let me give it a try

**Comment by cmorillas** [comment]
Fantastic. Thank you very much,

César
