### ISSUE TITLE
Suggestion: Adding a setItem method

### ISSUE THREAD

**Issue by perikorese** [lekoala/bootstrap5-tags#100]
It would be awfully nice if there in addition to addItem also was a setItem method, so that I could do:

const el = document.getElementById("modularbehaviour-choosecompany");

el.inst.setItem(7);

Where 7 is the value of the existing tag / option, that I want to select.

**Comment by lekoala** [comment]
addItem works for existing or new option regardless, so you should be able to do addItem(7) and it would just work

**Comment by perikorese** [comment]
Ah, OK.

If I just do `el.inst.addItem(7);` I just get 

`<option value="7" selected="selected">7</option>`

But I think I should do it like this:

`el.inst.addItem(label, value);`

It's for a form, where I edit some information and I get label and value from a database.

**Comment by lekoala** [comment]
i see i added this https://github.com/lekoala/bootstrap5-tags/commit/f786c241a9b2ff1996280543425ce7b7b7c2cbe8
you can try on master and see if that works better

**Comment by perikorese** [comment]
I did `npm install lekoala/bootstrap5-tags#master --save` and tried again, but I get the same result:

![Skærmbillede fra 2023-10-04 13-49-23](https://github.com/lekoala/bootstrap5-tags/assets/52708770/755e6351-79de-40e0-ac85-f4f537f5e1e4)

`<option value="9" selected="selected">9</option>`

**Comment by lekoala** [comment]
i updated the demo it seems to work fine?
https://github.com/lekoala/bootstrap5-tags/commit/e60e36cba8afc845801c88e8d67890ecf52362fc
can you give it a try?

**Comment by perikorese** [comment]
Hmm, I guess it makes a difference, that I use bootstrap5-tags with Modular Behaviour?

**Comment by lekoala** [comment]
here is a working jsfiddle

https://jsfiddle.net/4nap8o5e/

**Comment by lekoala** [comment]
and released just in case
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.6.10

if you can provide a non working example i'm happy to fix it otherwise that's all i can do for now :)

**Comment by perikorese** [comment]
Thanks for adding the setITem method. I do see that it works in the jsfiddle. In my case it doesn't work, but I'll figure out what the problem is in my case.

**Comment by perikorese** [comment]
I see now, that setItem works if I write the select options directly in the code as in the jsfiddle.

If I get the select options from a server via the data-server attribute in <modular-behaviour>, setItem doesn't work.

So just to sum my code up:

```               
<modular-behaviour id="modbeh_choose_category" name="category" src="//<%= process.env.BASE_URL %>/bootstrap5-tags/tags.min.js">

    <select
        id="category_select"
        name="categories[]"
        data-server="/json/categories"
        data-show-drop-icon="true"
        data-autoselect-first="false"
        data-max="1"
        data-allow-new="true"
        data-allow-clear="true"
        data-clear-end="true"
        data-badge-style="secondary"
        multiple
    >
        <option disabled hidden value=""></option>
    </select>

</modular-behaviour>
```

and:

```
$(document).on( 'click', '.edit_something', function(e){
    e.preventDefault();

    fetch('/data/somedata/', {
        method: 'GET'
    })
    .then((response) => response.json())
    .then((result) => {

        $('#somemodal').modal('show');

        const modbeh_category = document.getElementById("modbeh_choose_category");

        modbeh_category.inst.setItem(result[0].category_id);

    })
    .catch((error) => {
        console.error('Error:', error);
    });

});
```
