### ISSUE TITLE
scroll not working

### ISSUE THREAD

**Issue by f108156106** [lekoala/bootstrap5-tags#104]
https://jsfiddle.net/f83269Ly/

When I scroll dropdown of tags at bootstrap modal, The dropdown will disappear.

![PIC](https://github.com/lekoala/bootstrap5-tags/assets/96830956/c365f44a-4b78-406c-9989-527aa0c74e60)

**Comment by lekoala** [comment]
@f108156106 good catch, that's a tricky one. i never realized i could not trust the blur event of the input ^^
not sure what is the best way to deal with this, but in the meantime i added a global click handler on the document to blur things when needed instead. it's on master you can give it a try :)

**Comment by f108156106** [comment]
@lekoala add display: flex make clear button upper on baseline, you need to add "align-items-center".
![1700786438121](https://github.com/lekoala/bootstrap5-tags/assets/96830956/ea18ae61-b8e8-4d80-a98f-2cfc85959406)

**Comment by lekoala** [comment]
added in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.6.13

**Comment by f108156106** [comment]
@lekoala 
https://jsfiddle.net/k02yx617/

use 1.6.13 version exists problem.

1.scroll still not working.
2.This dropdown of single tag not collapse at choose.

**Comment by lekoala** [comment]
ahah yes it was fixed in .12 but broke again in .13 due to the focus event i added for the add on blur feature
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.6.14
this should do it
i really need to refactor this whole thing :)

**Comment by lekoala** [comment]
@perikorese  this seems to work in the jsfiddle no ?
https://jsfiddle.net/f83269Ly/

it does work for me in chrome at least

**Comment by perikorese** [comment]
@lekoala Yes, in the fiddle it works.

I am using this in the select-tag:

```
data-server="/some/url"
data-server-params='{"id":"0"}'
data-show-drop-icon="false"
data-autoselect-first="false"
data-allow-new="true"
data-allow-clear="true"
data-clear-end="true"
data-show-disabled="true"
data-add-on-blur="true"
data-badge-style="secondary"
multiple
```

**Comment by lekoala** [comment]
@perikorese mhhh i updated the demo, all working fine for me

<img width="637" alt="image" src="https://github.com/lekoala/bootstrap5-tags/assets/250762/a1181190-934d-4bc7-a900-3242df0e420d">

https://github.com/lekoala/bootstrap5-tags/commit/1c18786455dd72bfba1f7940d5b9cfb8e4d07f0b

can you show me how to replicate the issue?

**Comment by perikorese** [comment]
I did a little research and found out, that if do this in jQuery, it works, i.e. I can drag the scrollbar and click the arrows without it closing.

```
$('#editmodal').on('mousedown mouseup click', '#typetags .dropdown-menu', function(e) {
  e.preventDefault();
});
```
where `#editmodal` is a large modal with multiple bootstrap5-tags instances (Modular Behaviour) on various form fields and `#typetags` is a div that encloses the select-element and the ul with class `dropdown-menu`.

**Comment by lekoala** [comment]
@perikorese yes that makes sense. it's just very odd it's seems to be working fine when I try it. Do you have a jsfiddle or codepen where i could see the issue?

**Comment by perikorese** [comment]
I found out what the problem was in my project. It is not a problem in bootstrap5-tags.

The select elements with the problem was in an enclosing div with the attribute `tabindex="0"`. When I removed that attribute which is not needed, the problem was resolved.

**Comment by lekoala** [comment]
@perikorese oh that makes sense, good to know !

**Comment by f108156106** [comment]
@lekoala I still have this problem

**Comment by f108156106** [comment]
I have two environment
chrome 114.0.1823.37 working
chrome 127.0.6533.120 not working

**Comment by lekoala** [comment]
indeed, it seems chrome is now handling the target better in a modal
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.7.5
this seems to fix it for me
