### ISSUE TITLE
Version 1.6.12 - blur - add on tab

### ISSUE THREAD

**Issue by perikorese** [lekoala/bootstrap5-tags#105]
I see that with the new version 1.6.12, adding a new tag on tabbing to the next field doesn't work anymore.

Is that intended?

**Comment by lekoala** [comment]
probably a regression from the blur refactor. i will check it out

**Comment by lekoala** [comment]
should be good in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.6.13

**Comment by perikorese** [comment]
It is. Thanks.
