### ISSUE TITLE
option inside optgroup cannot auto-select

### ISSUE THREAD

**Issue by DrFlowil** [lekoala/bootstrap5-tags#108]
Hi,
Auto-select option on tags init works well when option isn't part of an optgroup.
But when inside an optgroup, it won't select.

Thanks !

**Comment by lekoala** [comment]
do you have an example with the issue? options in optgroup should work fine

**Comment by DrFlowil** [comment]
Thanks for your fast answer !

`<!doctype html>
<html>

<head>
	<meta charset="utf-8">
	<title>Document sans nom</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/js/bootstrap.bundle.min.js" type="module"></script>

    <script type="module">
        import Tags from "https://cdn.jsdelivr.net/gh/lekoala/bootstrap5-tags@master/tags.js";
        Tags.init("select", {
            selected: "1,3",
        });
    </script>

</head>

<body>

    <select class="form-select" multiple>
        <option value="1">test 1</option>
        <option value="2">test 2</option>

        <optgroup label="Group">
            <option value="3">test opt 3</option>
        </optgroup>
    </select>

</body>

</html>`

This code only shows "test 1" (not in optgroup), but not "test opt 3" (in optgroup).

Thanks a lot for your help !

**Comment by lekoala** [comment]
@DrFlowil good catch there, that's something i overlooked when implementing optgroups
should be fixed here https://github.com/lekoala/bootstrap5-tags/releases/tag/1.6.16

**Comment by DrFlowil** [comment]
Super ! J'essaierai tout ça rapidement !
Merci beaucoup Thomas pour ton script, et pour ta réactivité ! ;-)
