### ISSUE TITLE
How to add data attribute on input?

### ISSUE THREAD

**Issue by f108156106** [lekoala/bootstrap5-tags#111]
I want to use i18next change language,
but set placeholder is fixed text,
so How to add data attribute.

**Comment by perikorese** [comment]
I'm not the developer, but I'm also using i18next in a project with bootstrap5-tags and I can do this without problems:

`data-placeholder="<%= t('Text string for translation') %>"`

**Comment by f108156106** [comment]
@perikorese I use **setConfig** and **resetSearchInput** function change i18n.
