### ISSUE TITLE
Blur is broken on the modal demo

### ISSUE THREAD

**Issue by amazy** [lekoala/bootstrap5-tags#112]
Hi @lekoala and first of all, thanks for this great component.

I noticed that clicking outside the dropdown in a modal broke between v 1.6.15 and v 1.6.16 (and it's not working either with 1.7.1).
This happens in the demo.html -> click on `works in modal too`, open the drop down and click in the modal but outside the dropdown -> we expect this click to close the dropdown (this was the behavior up to v 1.6.15).

**Comment by lekoala** [comment]
oh you are right, i had to do something because clicking in the scroll menu was blurring the element but now it's not blurring at all ! it should be fixed now, provided you use a mouse. not quite sure if this works for touch device but that's already some progress.

**Comment by lekoala** [comment]
see https://github.com/lekoala/bootstrap5-tags/releases/tag/1.7.2

**Comment by perikorese** [comment]
Thanks for this update.
