### ISSUE TITLE
Pass through the title attribute for tooltips

### ISSUE THREAD

**Issue by tim1mw** [lekoala/bootstrap5-tags#113]
I have a use case where I need to pass through the title attribute to show tooltips against the dropdown list, however the title attribute seems to get lost. I've had a dig in the code and came up with a very simple patch (attached) that will take the title from the original &lt;option&gt; element and apply it to the containing &lt;li&gt; element of the tag list.

I'm using the &lt;li&gt; instead of the underlying &lt;a&gt; because the tooltips don't work on the &lt;a&gt; tag if the option has been disabled. I'm using the tooltip to explain why the option has been disabled so this is important.

[title.patch.txt](https://github.com/user-attachments/files/15551874/title.patch.txt)

**Comment by lekoala** [comment]
oh i see
never thought of that

i did this:
https://github.com/lekoala/bootstrap5-tags/commit/a668ad26d174d896d32301cb2ca8a482b186d27c

it basically means the tooltip will appear on the tag and while hovering in the menu
seems good to me :)
what do you think ?

**Comment by lekoala** [comment]
closing :)
