### ISSUE TITLE
Accessibility issue.

### ISSUE THREAD

**Issue by BeaBjorn** [lekoala/bootstrap5-tags#114]
Thanks for this amazing project!

I have found that there is an accessibility issue with the ul-element generated inside of the select drop down and this is causing an error when testing sites using [Wave](https://wave.webaim.org/) (accessibility tool). The error is due to the ul-element having a role of “menu” but the li-elements inside not having a role of “menuitem”.
There are two ways to resolve this issue:

1.  Remove the role of “menu” on the ul-element.
2. Change the role of the li-elements from “presentation” to “menuitem”.

Either of the above will resolve the error.
More information on this error can be found here: https://blog.pope.tech/2020/03/27/broken-aria-menu-example/ 

Again, thank you!

**Comment by lekoala** [comment]
thanks for this very useful feedback :-)

i have changed the role to menuitem in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.7.3

**Comment by BeaBjorn** [comment]
Thanks for looking into this so quickly. I can still see a role of "presentation" on my li-elements. I think it might relate to [this](https://github.com/lekoala/bootstrap5-tags/blob/master/tags.js#L1496).

**Comment by lekoala** [comment]
oh you are right i missed there was multiple places with this role
i've changed it for the li
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.7.4

**Comment by BeaBjorn** [comment]
Perfect, I can confirm the error is now gone and this issue thereby resolved. Again thank you for addressing this so quickly and thanks for a great project. All the best!
