### ISSUE TITLE
[Enhancement] Max number of tags

### ISSUE THREAD

**Issue by davebaol** [lekoala/bootstrap5-tags#13]
I'd like the capability to specify the maximum number of tags supported by the multiple select.
Maybe something like a new attribute  `data-max-tags`.
For instance, if 
- available options are: _apple_, _banana_, and _orange_ 
- `data-max-tags="2"`
- currently selected options are _banana_ and _orange_

then the user can't add _apple_ unless he/she removes something first.

This feature would be useful, for instance, when selected options are saved as colums in a relational db, especially if `data-allow-new="true"`

@lekoala  What do you think?

**Comment by lekoala** [comment]
That sounds like a good idea. Maybe there is a bit of ui as well to make clear that you cannot add more tags (maybe show a validation message ?). Feel free to make a PR :)

**Comment by davebaol** [comment]
Yeah I'll try to find the time for this on Christmas holidays :bowtie:

**Comment by lekoala** [comment]
you can have a look at https://github.com/lekoala/bootstrap5-tags/releases/tag/1.3.5 and tell me what you think
