### ISSUE TITLE
Add tag with ',' tab and/or space in addition to enter

### ISSUE THREAD

**Issue by cmorillas** [lekoala/bootstrap5-tags#15]
Hi again,

I think it could be interesting (when data-allow-new="true") to add a new tag with another key other tan 'enter'. At least I am thinking in comma, tab and may be space key too.

What do you think?

**Comment by lekoala** [comment]
yes I already thought about that, i can add a "data-separator"

**Comment by lekoala** [comment]
preliminary support in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.3.4

**Comment by cmorillas** [comment]
Great job,
How can I add two "data-separator"?. (For example space and coma)

**Comment by lekoala** [comment]
Not sure if this is really useful, but it's easy enough to add so you can use now | as a separator for separators :-)
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.3.6
