### ISSUE TITLE
[Bug] Removed tags cannot be readded

### ISSUE THREAD

**Issue by OHutchyHutch** [lekoala/bootstrap5-tags#16]
When a user adds a tag, then backspaces or clicks a button to remove it then the tag disappears from the list and cannot be readded. 

P.S. This project has been an absolute life saver for my project. Thank you!

**Comment by lekoala** [comment]
@OHutchyHutch that's odd. actually i just found out a regression in the latest release, i just fixed it. do you have more details? seems to work fine for me with the latest release

**Comment by OHutchyHutch** [comment]
@lekoala It seems that the regression being fixed also fixed this issue. Thank you!
