### ISSUE TITLE
[Issue] suggestionsThreshold is not applied when set in Global options

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#17]
I am setting some global options up when initializing the Tags object, but the expected results per the applied settings are not taking place. Only way settings are applied is when using data attributes.

For example:

`Tags.init(tagsSelector, {
        allowClear: true,
        suggestionsThreshold: 0,
    });`
 
doesn't work. So I need to explicitly set the data attributes on the element by either altering HTML code or tricking Tags before initializing by programmatically adding the attributes. Like this...
`document.querySelectorAll(tagsSelector).forEach(tagsEl => {
        tagsEl.dataset.allowClear = true;
        tagsEl.dataset.suggestionsThreshold = 0;
    });`

The expected result is that when initializing Tags with an options object, specified settings take effect on the UI as expected.

**Comment by lekoala** [comment]
that's really odd. in the demo i'm using

    Tags.init("select:not(.ignore-tags)", {
      clearLabel: 'Clear tag',
      allowClear: true,
    });

and for the following input

Tags (show all + custom colors)

i see the clear icon even though i don't have the data-allow-clear option set to true.

do you have a working example jsfiddle or something with the issue?

**Comment by jestrella04** [comment]
Further looking into this, seems like the issue is very specific to the "suggestionsThreshold" option. If set in the constructor it doesn't apply the intended behavior (display the selection popup on focus).

See an example below on jsfiddle.

[](https://jsfiddle.net/qns3zyh9/)

**Comment by lekoala** [comment]
Indeed! the constructor check was a bit naive
fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.5
