### ISSUE TITLE
[Issue] Disabled options on the original select element are visible/selectable on Tags UI

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#18]
When the original select element has one or more disabled options, after the Tags UI gets populated items matching the originally disabled options will be still visible and selectable thus leading to potential validation issues.

Users should not be able to select an option that is disabled, Tags should provide a way to either disable or hide options as needed.

**Comment by lekoala** [comment]
fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.3

**Comment by jestrella04** [comment]
Wow, superb. Thanks!
