### ISSUE TITLE
[Enhancement] Keep the selection popup on screen when the "Multiple" attribute is enabled

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#19]
It will be a super nice to have feature to have an option to keep the selection popup on screen after a selection is made and the "Multiple" attribute is set on the target element, so that the user doesn't have to manually trigger the popup for every selection to be made.

**Comment by lekoala** [comment]
mhh yes so what i did is keep it open if you set the threshold to 0 you can check in the demo
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.3
