### ISSUE TITLE
Pressing enter after tag was added adds the tag again

### ISSUE THREAD

**Issue by filips123** [lekoala/bootstrap5-tags#2]
If you add a predefined tag from the list, and press enter again, that tag will also get added again. This doesn't happen when you add a new tag.

Video below was recorded on the Codepen demo in "Tags new" input, but the same happens in the "Tags" input. First I added "Banana" tag which os one of the predefined tags and then pressed enter few times. The tag was also added multiple times. Then I refreshed the page and added "Test" tag which is a new tag and again pressed enter multiple times, but tag was not added.

https://user-images.githubusercontent.com/16626308/123546441-cbbc2400-d75c-11eb-827e-a366ec843bfc.mp4

Is it possible to prevent adding the same tag multiple times this way?

**Comment by lekoala** [comment]
Thanks for the detailed report. It should be fixed with https://github.com/lekoala/bootstrap5-tags/commit/18289b9fec05e8a92b992b1708de85cbd4139e02
