### ISSUE TITLE
[Issue] Tags fail to calculate the input size if the original list is empty

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#20]
When working with an empty select list to let the user enter as many tags as they wish, Tags will fail to properly calculate the input size and will throw an error in the console as follows:

`Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Tags.#adjustWidth (app.js:...)
    at Tags.#configureSearchInput (app.js:...)
    at new Tags (app.js:...)
    at Function.init (app.js:...)
    at HTMLDocument.<anonymous> (app.js:...)`

**Comment by lekoala** [comment]
yes the use case is to provide at least one option for the placeholder but we might as well deal with empty lists
fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.3
