### ISSUE TITLE
[Enhancement] Query server response as the user types in

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#21]
Currently, there's only an all or nothing way to retrieve resources from the server, which in turn can be counter productive when retrieving lots of data. Will be nice to have feature to allow to query server as the user types in so that data is returned in small chunks.

**Comment by lekoala** [comment]
you can set data-live-server to 1 and filter the list according to the parameter being sent to the server. it's a little basic i admit but it should do the job

**Comment by jestrella04** [comment]
Let me give it a try, I'll go ahead and close in the meantime.
