### ISSUE TITLE
[Issue] Placeholder is not displayed after clearing all tags from a field

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#22]
Placeholder displays properly on page load, but after all tags are cleared from a field it will remain empty until a new tag is selected. Ideally, placeholder should display whenever there is no value attached to a field.

**Comment by lekoala** [comment]
do you have an example? it's working great for me :)

**Comment by jestrella04** [comment]
It happens when deleting tags one by one (when data-allow-clear="true"). If using the Reset button the placeholder is properly restored. If this still doesn't make sense I'll create a jsfiddle for you.

**Comment by lekoala** [comment]
ah yes i see! if you click on clear indeed. fixed
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.4
