### ISSUE TITLE
[Enhancement] Watch for changes on the original select element and update Tags accordingly

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#23]
Select options are often loaded dynamically by an ajax call or an event tied to it or a related element. Will be a very nice feature to have if the Tags UI gets updated whenever the original element is updated (options added/deleted or option attributes disabled/hidden changed).

**Comment by lekoala** [comment]
What i can do is provide a "resetSuggestions" method that will basically do what is happening in the constructor. it will have to be called manually after update.
otherwise it requires to have some kind of mutator observer in place and that's maybe too complex for its purposes

**Comment by jestrella04** [comment]
Agree with your last statement, anyways, a resetSuggestions method will be greatly appreciated as well. :)

**Comment by lekoala** [comment]
Added in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.6 you can check the demo to see how it works
