### ISSUE TITLE
[Issue] Change event fired from Tags does not bubble up to document root

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#24]
It's common practice, at least for me, to listen to event updates directly on the document selector rather than on each individual element dispatching. This allow me to sort of of standard way to listen for event for both static and dynamically loaded DOM elements. The issue with tags is that the event is not bubbling up all the way up to the document element so I am not able to capture the change event without major refactoring of my code. I have created a Jsfiddle illustrating my point, see below:

https://jsfiddle.net/unckv93h/

See that nothing is logged to console when adding the event listener right into the document selector.

**Comment by lekoala** [comment]
fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.8.. passed the bubbles option to dispatchEvent instead of being in the event constructor^^
