### ISSUE TITLE
[Issue] Placeholders is still visible after a selection is made

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#28]
This is specific to 1.4.10, after a selection is made the placeholder is still visible. Placeholders should only be visible when no selection is made.

**Comment by lekoala** [comment]
sorry about that i commented the selected attribute to make a test and forgot to uncomment it :-)
should be alright https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.11
