### ISSUE TITLE
[Enhancement] Allow to programmatially clear all selected values

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#33]
I'm trying to find a way to programmatically clear all selections and display the placeholder back. Not just like a reset to default values since there will be cases where selected values are not valid anymore.

I see a removeActiveSelection method but that didn't do the trick for me, there's also a removeAll method but it seems a little extreme for this use case.

**Comment by lekoala** [comment]
What's wrong with removeAll ? I agree that selecting all the span is not great but otherwise just call removeitem in a loop with getselectedvalues. If you find a better way happy to merge any PR :)

**Comment by jestrella04** [comment]
Looking at it, it seems removeAll is all I need, if it just restores the placeholder on clear. :P

**Comment by lekoala** [comment]
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.13 done! i've cleaned up the method as well, this span selecting thing wasn't great
