### ISSUE TITLE
[Issue] Single select with a placeholder still defaults to first option

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#34]
When you declare an empty option to use as a placeholder on a single select element, even tho the placeholder is displayed properly, if you try to get the value of the element you will confirm that it's taking the value from the first not empty option.

On a similar note, and I believe this is new to this version, a single select with no placeholder doesn't display the first available option as expected.

JSFiddle ahead... https://jsfiddle.net/xkr5uyLe/

**Comment by lekoala** [comment]
indeed... i stopped using selectedOptions but it seems that the best way to get the initial value, so i went back to use it.
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.14
