### ISSUE TITLE
[Issue] data-separator is not working on Chrome for Android

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#36]
As weird as it seems, data-separator is not working on Chrome for Android: the only tags that will be selected are the ones picked from the dropdown, so you are not allowed to enter tags on the fly. This is working perfectly fine on Chrome desktop.

**Comment by lekoala** [comment]
Soo i've discovered the happy and broken world of mobile keyboards^^
Took three attempts to fix it, but it seems to work !
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.17
