### ISSUE TITLE
[Issue] The selection popup does not remain open on select boxes allowing multiple selections

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#37]
When multiple selections are allowed, the selection popup is closed every time a selection is made, and in order for it to be displayed again you have focus out of the element and then focus back into it.

**Comment by lekoala** [comment]
mhh i see i removed a dispatch event that was supposed to stay ;-) i added a comment so that i don't do that in the future
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.19
