### ISSUE TITLE
Cannot insert new tag if the new tag is substring of other tags

### ISSUE THREAD

**Issue by benwong01f611** [lekoala/bootstrap5-tags#38]
From demo.html, there are 3 options, "Apple", "Banana", "Orange".
If I would like to insert a new tag called "an", it will highlight "Banana" in suggestions as shown below. Pressing enter would choose "Banana" but not the new tag "an".
![image](https://user-images.githubusercontent.com/23426279/150316753-1cf45787-0c54-4fa9-905b-8917e3b523c0.png)

Is it possible for users to press escape to hide the menu? Or not selecting any options by default?

I do not know JavaScript well, but i have tried adding few lines of codes and it worked for me:
```js
// Other key handlers
// After line 364
case 27:
case "Escape":
  this.#hideSuggestions();
  break;

**Comment by lekoala** [comment]
@benwong01f611 it's a bit of a edge use case but why not, it doesn't hurt to add it and your solution works well
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.21
