### ISSUE TITLE
Styling Functionality

### ISSUE THREAD

**Issue by TK20466** [lekoala/bootstrap5-tags#39]
Marvelous plugin.  I see there's a way to add a custom class, however one cannot add multiple classes.

IE:
`data-badge-class="text-dark someOtherClass"`

Will throw an error:  `Failed to execute 'add' on 'DOMTokenList': The token provided ('text-dark someOtherClass') contains HTML space characters, which are not valid in tokens.`

Could a split of some form be added for when multiple classes would be useful?

Further, is it possible to style the dropdown suggestions with the same class?

**Comment by lekoala** [comment]
yes it should be fairly easy. currently i'm pushing the class
https://github.com/lekoala/bootstrap5-tags/blob/37e68e1bdbfcbe01313f3b2de586d8bbaeec7b8c/tags.js#L784-L786
be we could split the string and push multiple parts

**Comment by lekoala** [comment]
added in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.22
