### ISSUE TITLE
Enter and backspace key not detected in mobile

### ISSUE THREAD

**Issue by fahmij8** [lekoala/bootstrap5-tags#4]
First off all, amazing work dude!
But, I encounter some problem using this library which is as it says in the title. Luckily I know the way around that. Which is to use `event.keyCode` rather than `event.code` on input keydown event and it works. I would love to make a pull request but I would like to hear some feedback first, Cheers🍺.

**Comment by lekoala** [comment]
i haven't tested on mobile, but sure a PR is welcome if it fixes the issue :)

**Comment by fahmij8** [comment]
Just a quick reminder you haven't publish this package, and I believe it's an important update

**Comment by lekoala** [comment]
@fahmij8 published ;-)
