### ISSUE TITLE
Apply input as tag on blur event

### ISSUE THREAD

**Issue by chrischi1989** [lekoala/bootstrap5-tags#40]
Is it currently possible to apply the input as a tag when the blur event occurs on the input field?

Best regards

**Comment by lekoala** [comment]
No it's not currently possible. Not sure it's a good idea either. But it should be possible to manually add the item on blur if needed.

**Comment by chrischi1989** [comment]
Ok, I was just asking because a friend of mine tested a tag input on my project yesterday. He wrote a tag (without pressing enter or entering a comma) and submitted the form straight away. Therefor the server didn't receive any tags. I don't know if this use case is common on a larger scale but that's why I thought it would be nice if the tags may be applied on the blur event.

**Comment by lekoala** [comment]
As long as it does not look like a badge, it's not saved. Actually it may even be strange to actually register tags that haven't been validated but I get your point maybe some people could find it useful. I'll update the demo to show how to do it and update the library if it's not possible

**Comment by chrischi1989** [comment]
Thanks for your effort. I already came up with a solution for my use case:

```javascript
document.querySelector('#tags-input + .form-control input').addEventListener('blur', function() {
    this.dispatchEvent(
        new KeyboardEvent('keydown', {
            code: 'Enter',
            key: 'Enter',
            charCode: 13,
            keyCode: 13,
            view: window,
            bubbles: true
        })
    );
});
```

**Comment by lekoala** [comment]
Good job 👍
