### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by dizpatcher** [lekoala/bootstrap5-tags#41]
Please, check your demo page - the package functionality is displayed incorrectly there

**Comment by lekoala** [comment]
@dizpatcher what is incorrect? any example? error message?

**Comment by dizpatcher** [comment]
<img width="1476" alt="Снимок экрана 2022-02-09 в 13 03 54" src="https://user-images.githubusercontent.com/46828883/153175650-a9a2d7c6-8f33-41d7-a807-f65629f52d64.png">
There is no package effect

**Comment by lekoala** [comment]
@dizpatcher any error message in the console log? which browser are you using? it IS working on a modern browser, so the question is not about "it works/it doesn't work" but WHY it doesn't work for you :)

**Comment by dizpatcher** [comment]
Safari 14.0.1 
Console: SyntaxError: Invalid character: '#'

**Comment by lekoala** [comment]
@dizpatcher yes, i'm using private class methods
https://caniuse.com/mdn-javascript_classes_private_class_methods
it requires safari >=15

if you build from source, you can always target a lower version (es2020) which will convert the private class methods but it adds about 3kb and use weakmaps

i'm still a bit unsure if I should go back to regular class methods to make the default compatibility better

**Comment by dizpatcher** [comment]
Okay, thanks for helping me figure it out. This is your right.

**Comment by lekoala** [comment]
@dizpatcher so i've replaced the # with _ and mangled properties instead. it should work better now :-)
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.23
