### ISSUE TITLE
Getting live results from server

### ISSUE THREAD

**Issue by benf101** [lekoala/bootstrap5-tags#42]
I am attempting to get the live tag suggestions from my database. I think I have it _almost_ working... Using the debugger, I have found that results are being returned to the browser in JSON format, but the web page still doesn't show any drop down with suggestions.

The "read me" page doesn't give details on the expected structure of the JSON results coming from a server. The structure I have chosen was just a wild guess so it is most likely the problem.

The structure looks like this: {"3":"work","4":"home"}

Or generally speaking, this format: {database_id: tag_name, database_id: tag_name}

Is that structure the problem?

Also, is there a more detailed instructional page that goes into more detail than the github read me page?

Thanks for your help!

**Comment by benf101** [comment]
I figured out the format that works is this:
```
[{"value": "3", "label": "tag1"},{"value": "4", "label": "tag2"}]
```

Now it's working.

**Comment by lekoala** [comment]
@benf101 yes that's the right one. I think the demo.json is quite self explanatory but maybe I should add something in the readme as well ;-)

**Comment by benf101** [comment]
> @benf101 yes that's the right one. I think the demo.json is quite self explanatory but maybe I should add something in the readme as well ;-)

As far as I can tell, the demo doesn't have an example of live server data, and does not use JSON as a data source. I had to look at the source javascript. When I found `suggestion.value` and `suggestion.label` I finally figured it out.

Anyway, it's working now and I'm happy about that, and grateful for your project. Thank you!
