### ISSUE TITLE
Validation Regex

### ISSUE THREAD

**Issue by benf101** [lekoala/bootstrap5-tags#43]
What is the correct way to use the regex validation? I think I've tried every possible option and nothing seems to do what I want. It either has no effect, or it prevents all entries.

Using this code:
`select_el.setAttribute("data-regex", /[A-z]/);`

I have confirmed through the Tags class using `console.log("REGEX: " + this.validationRegex);` that my regex value is being passed into the Tags class, but as stated above, the outcome not right.

I have tried it with/without quotes, with/without "gi", with/without brackets, and probably other ways too. I'm out of ideas.

Thanks for your help.

**Comment by lekoala** [comment]
Did you look at the demo ? Here is an example

data-regex=".*@mycompany\.com$">

Last time I tried it was working

**Comment by benf101** [comment]
All this time I thought "the demo" was the codepen link in the readme file, but there is actually a file called "demo". So yeah, that helps, and I got it working now.

Thanks.
