### ISSUE TITLE
[enhancement] Server side: support custom column names

### ISSUE THREAD

**Issue by mariusa** [lekoala/bootstrap5-tags#44]
Hi,

Server side should provide an array of value/label objects. 

Would it be possible to please have new constructor options which say what server-side fields map to value/label? 
eg `valueField: 'id', labelField: 'title'` 

Thanks!

**Comment by lekoala** [comment]
added in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.26 let me know if that works for you

**Comment by mariusa** [comment]
Hi & thanks!

This doesn't work yet, as there are some places which still reference the hardcoded `value` field:

https://github.com/lekoala/bootstrap5-tags/blob/c4d5d39dd167f15bfd96321dbaad59d0fe8b07fd/tags.js#L277

https://github.com/lekoala/bootstrap5-tags/blob/c4d5d39dd167f15bfd96321dbaad59d0fe8b07fd/tags.js#L282

https://github.com/lekoala/bootstrap5-tags/blob/c4d5d39dd167f15bfd96321dbaad59d0fe8b07fd/tags.js#L233

https://github.com/lekoala/bootstrap5-tags/blob/c4d5d39dd167f15bfd96321dbaad59d0fe8b07fd/tags.js#L486

**Comment by lekoala** [comment]
only the last one was an issue, the others are regular html options. should be good now

https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.27

**Comment by mariusa** [comment]
Works now, thanks!
