### ISSUE TITLE
The tags input field width is too short when Non-ASCII value was input.

### ISSUE THREAD

**Issue by neko0318w** [lekoala/bootstrap5-tags#52]
The width looks fine when English was input, but when you input Korean or some other foreign language the tags input field shows shorter than its supposed to be

[Image]
![image](https://user-images.githubusercontent.com/19932950/163969378-70689c94-3027-4b3e-8efd-7d965ed44773.png)
![image](https://user-images.githubusercontent.com/19932950/163969548-c9538f2e-eabe-4660-b7c2-cd1e714a9098.png)

[My Solution]
Looks natural when 'length + 1' was replaced to 'length * 2' in _adjustWidth expression

**Comment by lekoala** [comment]
that's odd! so a character is larger than a size of 1 ? well I guess having a size 2 doesn't hurt either, i'll make the update :)

**Comment by lekoala** [comment]
hopefully fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.30

**Comment by lekoala** [comment]
mhh giving a second look i read + 2 not * 2 ... mhh might not be ideal for longer inputs then

**Comment by lekoala** [comment]
Yes, I guess there is no way around actually measuring the font. The size attribute doesn't seem accurate at all in this case.
I've just published https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.31 which seems to work fine and updated the demo accordingly

**Comment by neko0318w** [comment]
Thank you! for your hard work.
This issue has been resolved.

One more, placeholder the same thing is happening.

**Comment by lekoala** [comment]
I will look into it. Actually I'm thinking to switch to a contenteditable div so that it all happens automatically. I'll test that first and based on that will advise.
