### ISSUE TITLE
Missing server side features

### ISSUE THREAD

**Issue by AlexDupreWeb** [lekoala/bootstrap5-tags#53]
Hy, I spent part of my day implementing this library. It's really nice to use. But for me it's missing an important element: we can't initialize the input field with selected value (with JSON or with init function).

It's really a pity !

This issue is just an idea for improvement, if you want to implement it I am available to test. Otherwise you can close it.

Have a nice day !

**Comment by lekoala** [comment]
that should be fairly easy to add, let me have a look :)

**Comment by lekoala** [comment]
this should do it
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.33
