### ISSUE TITLE
Strange Error using Example Code

### ISSUE THREAD

**Issue by scath999** [lekoala/bootstrap5-tags#58]
This package looks exactly like what I'm looking for.
To test integration with my project, I copied and pasted some example code found in the [demo](https://codepen.io/lekoalabe/pen/ExWYEqx)

Works fine, but I get a truncated "undefined" tag in the list with no background, no matter what I do.

![image](https://user-images.githubusercontent.com/38800373/187803685-a8710873-be09-4d58-800d-1d70867c7e1a.png)

The code generated for that 'undef' element is 

`
<input type="text" autocomplete="off" spellcheck="false" aria-label="Type a value" placeholder="" size="1" style="background-color: transparent; border: 0px; outline: 0px; max-width: 100%; min-width: 8px;">
`

I've looked for guidance (searching for "Bootstrap tags lekoala 'undefined'"  and other permutations) but can't find any help.

I may be missing something here, but (respectfully) this looks like a bug. 

Any help?

Platform: Win10
JQuery: 3.6
Bootstrap: 5.1

**Comment by scath999** [comment]
Strange. When I populate with data from my backend it works perfectly. 

Closing.

**Comment by lekoala** [comment]
@scath999 that's an odd one :)

the input is the one i use to type the text, it seems that somehow you get an undefined value
the only line that can do that is when you paste something or have an input event

          this._searchInput.value = this._searchInput.value.slice(0, -1);

but even then i'm not sure what it's not working ;-) let me know if you get the issue again, it should be fairly easy to debug there are only a limited number of places where that could come from

**Comment by scath999** [comment]
@lekoala I'll keep an eye out - very kind of you to follow up.

Cheers!
