### ISSUE TITLE
Displaying selected items when using the data-selected option

### ISSUE THREAD

**Issue by pnr32** [lekoala/bootstrap5-tags#59]
We use the following code:
```
<select
    class="form-select w-auto"
    id="new-task-regions"
    name="new-task-regions"
    multiple=""
    data-server="https://mocki.io/v1/0c5b5251-b7d6-4be8-9d11-304fd930171a"
    data-allow-clear="true"
    data-clear-end="true"
    data-live-server="true"
    data-full-width="true"
    data-suggestions-threshold="0"
    data-show-all-suggestions="true"
    data-keep-open="true"
    data-selected="1"
    style="display: none"
  ></select>
```

[View on Codepen](https://codepen.io/ap-optimism/pen/wvjRNEj)

The pre-selected tag from data-selected attribute is not displayed during initialization.
It is displayed only after entering any character.

How fix it?

**Comment by pnr32** [comment]
The problem is relevant only when using the liveServer option is true.

**Comment by lekoala** [comment]
@pnr32  this should fix it
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.39

**Comment by pnr32** [comment]
@lekoala , in the example presented [earlier](https://codepen.io/ap-optimism/pen/wvjRNEj), tags from the data-selected attribute are also not displayed.

**Comment by lekoala** [comment]
data-selected is fundamentally incompatible with live server which returns a filtered list
if the json returned by the server should populated the default selected options, then you need to disable live server

**Comment by lekoala** [comment]
i guess that technically, if you use suggestions-threshold="0" then the "live server list" is not filtered and therefore we could enable this... mhh i need to look into it :-)

**Comment by lekoala** [comment]
closing for now ;-)
