### ISSUE TITLE
I want to update the options of the select(s) dynamically and then re-init or update the instances.

### ISSUE THREAD

**Issue by geerdes** [lekoala/bootstrap5-tags#60]
This plugin workes so well but I ran into a problem. I want to dynamically update the options of the select(s) as soon as the the change event on the select has fired. In fact, I update the disabled attribute of some options. And then I wanted to re-run the Tags.init() because there is no update() function. So I removed the tags from the DOM and then ran init(). The problem is, that within the INSTANCE_MAP the firstly created instances still exists, so init() will skip the creation of new Objects. Any suggestion? Maybe @lekoala adds a static update() function? That would be the cleanest way.

**Comment by lekoala** [comment]
@geerdes if you use dispose() it should be removed from the map, no?

**Comment by lekoala** [comment]
also resetSuggestions should be fine as well

**Comment by lekoala** [comment]
Tags.getOrCreateInstance should do the trick 
it basically works just like any bootstrap component

**Comment by geerdes** [comment]
Thanks, got it work with `var obj_someName = Tags.getInstance(document.querySelector('#some_id'))` --- I don't know why, but I had a problem using obj_someName.resetSuggestions(); inside a function, but I got it work.
