### ISSUE TITLE
Dark theme text color

### ISSUE THREAD

**Issue by visavi** [lekoala/bootstrap5-tags#65]
Hello, happy holiday, there is a little problem if you enable the dark theme in bootstrap 5.3
The color of the text cannot be made light
Can anything be done about it?

[Запись экрана от 2023-01-07 19-11-45.webm](https://user-images.githubusercontent.com/826831/211160192-52a35eeb-1276-44d7-8f8f-3cbcf23ed63d.webm)

```
.form-control-focus {
    color: var(--bs-body-color); <- not worked
    background-color: var(--bs-form-control-bg);
    border-color: rgba(13, 110, 253, .5);
    outline: 0;
    box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, .25);
}
```

**Comment by lekoala** [comment]
@visavi well, it's still in alpha :-)
but it's an easy fix, you can have a look on master and tell me if that works the way you want

**Comment by visavi** [comment]
Yes, everything works fine, thanks

**Comment by lekoala** [comment]
published in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.2
