### ISSUE TITLE
Possibility to add same tag multiple times

### ISSUE THREAD

**Issue by halali** [lekoala/bootstrap5-tags#67]
Hi,

i would like to have setting to enable possibility to add one tag more times

**Comment by lekoala** [comment]
@halali that is going to be really difficult since this is based on a select element that doesn't allow same values multiple times

if I decouple the script for the select tag, then it becomes possible

**Comment by halali** [comment]
maybe there should be small hack... on select item it will add same item to select element and remove one on clear

is that solution possible ?

**Comment by halali** [comment]
@lekoala damn you are fast, thanks work as expected...

Will do more test next week...

just an question... will be possible add custom event for `select tag` and `clear tag` so i can run function when tag is selected and another when tag is cleared from select.

**Comment by lekoala** [comment]
@halali indeed, should be fixed on master now

**Comment by halali** [comment]
@lekoala i can confirm. work now

what about event for select, remove tag ?
should i open another FR or is not planed ?

of course i can handle it by change event, but i need to compare arrays what was added or removed.

**Comment by lekoala** [comment]
@halali there is already a onSelectItem(item) callback
I just added the onClearItem(value) as well on master

if you see anything else let me know

**Comment by halali** [comment]
Thank you.

I will close this as resolved.

**Comment by halali** [comment]
Hello again, onClearItem event dont work if you use backspace to clear item and not X

**Comment by lekoala** [comment]
Fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.4

**Comment by halali** [comment]
Thanks, work perfectly
