### ISSUE TITLE
Support for Bootstrap 5 Floating labels

### ISSUE THREAD

**Issue by dtanase** [lekoala/bootstrap5-tags#68]
Hello 

Would it be possible to add support for the Floating labels of Bootstrap 5? 

Thank you!

**Comment by lekoala** [comment]
@dtanase i just gave it a try, and it you follow how a floating select would be done, it seems to work fine
it looks like this. you can check the updated demo.html
<img width="459" alt="image" src="https://user-images.githubusercontent.com/250762/216913681-911f4422-4915-49af-8842-b99a90392b39.png">

but it's going to be more like a select rather than an input. Is that what you had in mind?

**Comment by dtanase** [comment]
Hello @lekoala!

Thank you for the quick answer.

What I mean, when empty, the label should take the place of the placeholder and "fly up" when the select has focus, as it is for the other input element:

![image](https://user-images.githubusercontent.com/17724363/216970404-fba459dc-25e4-4a30-9151-c4864dbecf1e.png)

However, on a second check, I am not sure if the select input has this behaviour to begin with, so I am not sure it actually depends on the library or on the bootstrap itself.

What do you think?

Thank you,
Dorian

**Comment by lekoala** [comment]
i see
it's not possible "out of the box" but support is easy enough to add with a few lines of css
i added a custom class to add pseudo placeholder-shown support. it's on master. not sure it's interesting but it doesn't take much to support it so...

<img width="263" alt="image" src="https://user-images.githubusercontent.com/250762/217777596-29dd8447-f89a-48c6-948c-9a098331dbd2.png">

**Comment by dtanase** [comment]
This looks amazing! 

For the future generations of floating users, one must not forget the `form-floating` css change (visible clearly in the demo.html), else it won't work properly.

Thank you very much @lekoala !

**Comment by lekoala** [comment]
published and released in 1.5.5 amongst other improvements ;)

**Comment by dtanase** [comment]
@lekoala thank you!
