### ISSUE TITLE
Problem with showing dropdown with arrow down in versions after 1.4.42

### ISSUE THREAD

**Issue by perikorese** [lekoala/bootstrap5-tags#69]
If I use a version of bootstrap5-tags after 1.4.42, either via CDN or from the node module, the dropdown on pressing arrow down stops working.

I use Module Behaviour.

**Comment by lekoala** [comment]
mhhh good catch
this should be fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.6

**Comment by perikorese** [comment]
> mhhh good catch this should be fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.6

I updated the node module and it works.

Thanks a lot.
