### ISSUE TITLE
How to Add/Set tag using Javascript?

### ISSUE THREAD

**Issue by JobberRT** [lekoala/bootstrap5-tags#78]
Hi, I wonder how to add new tag or select existing tag using javascript? Didn't see this feature in README

**Comment by lekoala** [comment]
something along these lines

https://github.com/lekoala/bootstrap5-tags/blob/6559b53694b136421bd1a61d2ca32c9dd23074a8/demo.html#L200-L214

**Comment by lekoala** [comment]
i could wrap this in a simple api if the feature is useful enough

**Comment by JobberRT** [comment]
@lekoala Thanks for the snippet.

And if you could wrap this into a api, that would be very nice. Let me give you some senario that I just came into:

1. Saved something into DB via a form containing bs5-tags element(For example, `a list of url`, `a list of user customized skills`, `a list of avaiable option`)
2. Read saved data from DB, and render it into element for seeing/updating the data.

**Comment by JobberRT** [comment]
@lekoala Thanks! I've got busy on other things these days, sorry for the delay!
