### ISSUE TITLE
Input invalid when there's one item and not entered.

### ISSUE THREAD

**Issue by JobberRT** [lekoala/bootstrap5-tags#79]
Thanks for this awesome Bootstrap5&Vanlina JS library!!! Here's a problem when I using it: 
`Tags.js see single input with not entered as invalid.`

Example: 

**Invalid(not exist in `new FormData` or direct submit form)**
![image](https://user-images.githubusercontent.com/17498767/230774548-5c7407fc-50c5-469e-9248-4671520312b3.png)

**Valid**
![image](https://user-images.githubusercontent.com/17498767/230774582-0f4e74e6-f5a5-484f-aa3c-ceda57f788a3.png)

I think Tags.js gives people the **chance** to input muliple value, but they should still have the ability to input a single value without additional operation(after input the value, seperat it by comma or blank or enter to make it a tag).

Hope Tags.js can add this simple behavior to automatically turn single value to a valid tag(Or just make it appeal when create a FormData or submit the form)

**Comment by lekoala** [comment]
isn't that what 'addOnBlur' setting does?
