### ISSUE TITLE
Regex validation not applied when using separator?

### ISSUE THREAD

**Issue by axllent** [lekoala/bootstrap5-tags#80]
Thanks for this awesome library! One issue I'm facing is that the regex validation isn't being applied when I'm using any separator other than the enter key (or blur). Am I missing something? In the example below, I have a comma as a separator, and whilst that works, it simply bypasses the regex. I have tried 1.5.15 but the issue remains.
```html
<select class="form-select tag-selector" multiple
    data-allow-new="true"
    data-clear-end="true" 
    data-allow-clear="true" 
    data-placeholder="Enter tags..."
    data-add-on-blur="true"
    data-badge-style="primary"
    data-regex="^([a-zA-Z0-9\-\ \_]){3,}$"
    data-separator="|,|">
    ......
</select>
```

**Comment by lekoala** [comment]
@axllent good catch ! indeed, i've changed a bit how to deal with new tags and only them get validated and i wasn't flagging them properly. it's fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.17

**Comment by axllent** [comment]
Thank you, works perfectly!
