### ISSUE TITLE
Remove debugging console.log(focus|blur)

### ISSUE THREAD

**Issue by axllent** [lekoala/bootstrap5-tags#81]
There appear to be two debugging console.log() functions in both the tags.js and tags.min.js builds which should probably be removed, namely [`console.log("focus");`](https://github.com/lekoala/bootstrap5-tags/blob/0f254d3ce1c20091793143371b69f5d31753655d/tags.js#L607) and [`console.log("blur");`](https://github.com/lekoala/bootstrap5-tags/blob/0f254d3ce1c20091793143371b69f5d31753655d/tags.js#L616) which cause unnecessary browser "noise", and were likely just forgotten about during development I suspect. If these are handy for development, then I would suggest a new element data tag `enableDebug` or similar to turn that on :+1:

**Comment by lekoala** [comment]
wwhooops sorry about this :)
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.16
