### ISSUE TITLE
Delete console.log

### ISSUE THREAD

**Issue by Gaetanbrl** [lekoala/bootstrap5-tags#84]
Hi,
Some `console.log` still in release :

https://github.com/lekoala/bootstrap5-tags/blob/master/tags.js#L671

and 

https://github.com/lekoala/bootstrap5-tags/blob/master/tags.js#L661

**Comment by lekoala** [comment]
@Gaetanbrl sorry about that, i should pay more attention

i added a unit test next time i won't miss it ;-)
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.20

**Comment by Gaetanbrl** [comment]
Thanks a lot !
