### ISSUE TITLE
Contribution infos

### ISSUE THREAD

**Issue by Gaetanbrl** [lekoala/bootstrap5-tags#87]
Hi!

Have you a section like "How to contribube ?" or "how to build" according to explain dev env install (e.g node version, npm commands to install, npm commands to build min files...)  if some need to contrib ?

**Comment by Gaetanbrl** [comment]
What is the process to build files ? (e.g `tags or tags-standelone` files).

**Comment by Gaetanbrl** [comment]
With minimal info to contribute, I could have treated #84  alone / fastly with a PR.

**Comment by lekoala** [comment]
:-) there is no build process you have to follow you can simply make a PR with your changes in tags.js, that's as simple as that
if you want to test your changes, run npm start
i'm going to add that to the readme

https://github.com/lekoala/bootstrap5-tags/commit/153cb5583bf031c0c3e3fad79b26844a104c2737

if you think anything is unclear, you can also make a pr to the readme ;-)

**Comment by Gaetanbrl** [comment]
> if you think anything is unclear, you can also make a pr to the readme ;-)

Ya thanks.
