### ISSUE TITLE
Add Config Variable for _getBootstrapVersion

### ISSUE THREAD

**Issue by KodaCHC** [lekoala/bootstrap5-tags#88]
Hi

Great Script. Do you see a way to add a variable in the configuration to override the bootstrap version in _getBootstrapVersion?

If I use a template based on Bootstrap 5, it may not recognize the desired version.

**Comment by lekoala** [comment]
version 5 is the default version
the function is only there if you have jquery and the jquery plugin, which is only for bs4

**Comment by KodaCHC** [comment]
Danke. jQuery ist integriert. Daher erkennt er mir wohl die Version 4.

**Comment by lekoala** [comment]
$.fn.tooltip.Constructor.VERSION.charAt(0) this should give you 5, not 4, if you are using bootstrap 5. I added jquery on the demo page just to be sure
