### ISSUE TITLE
force default values

### ISSUE THREAD

**Issue by Gaetanbrl** [lekoala/bootstrap5-tags#89]
Hi ! 

I have a classic `<select>` with some default selected `<options>`.

Next, i activate the tags with : 

```
        // => 2 selectedOptions
        let tagsTarget = document.getElementById(this.uuid)?.selectedOptions;
        // init
        Tags.init(`.${this.classId}`, {
            activeClasses: ["activeMultiSelectTag"],
        });
```

But the Tags.js seems only keep one selectedOptions and lose one after passing in this method : 

`this._configure(config);`

So, with this code : 

https://github.com/lekoala/bootstrap5-tags/blob/master/tags.js#L295

```
    console.log(this._selectElement.selectedOptions);
    this._configure(config);
    console.log(this._selectElement.selectedOptions);
```

... i get : 

![image](https://github.com/lekoala/bootstrap5-tags/assets/16317988/aaba0893-3b5a-4132-b48e-5326de1a97fb)

### Question

Whats is the good way to use default selected options with `Tags.init(".mySelector")` ?

I have saw selected option, but not sur to understand really how to use it because this test seems not works : 

`<select selected='val1,val2'>`

**Comment by Gaetanbrl** [comment]
I got it ! 

https://github.com/lekoala/bootstrap5-tags/blob/153cb5583bf031c0c3e3fad79b26844a104c2737/tags.js#L504

Code force to use fiestOption in my case, i dunno why, maybe i need to config this ? I will check lib options.

**Comment by Gaetanbrl** [comment]
Fixed by set the placeholder.

### Fix : 

Replace `<select id="myId">`

by 

`<select placeholder="random text" id="myId">`

**Comment by Gaetanbrl** [comment]
in addition, the `autoselectionFirst `option set to `false `is ignored.

**Comment by lekoala** [comment]
merged and published :)

**Comment by Gaetanbrl** [comment]
> merged and published :)

Thanks
