### ISSUE TITLE
Issue with click on dropdown item

### ISSUE THREAD

**Issue by davebaol** [lekoala/bootstrap5-tags#9]
Just noticed that if you click on an item of the dropdown and don't release the mouse button immediatly (literally) the dropdown close without adding the tag. You have to click very fast to make it work; which is a bit annoying.
You can easily reproduce the issue on the online demo.
It happens in my code too.

**Comment by lekoala** [comment]
Fixed in 1.2.1

**Comment by lekoala** [comment]
actually I realized that the mousedown event was causing the lost of focus on the searchInput. I even cleaned up things a little bit in 1.2.2 which should be even better
