### ISSUE TITLE
Allow selection of an existing value by input

### ISSUE THREAD

**Issue by Gaetanbrl** [lekoala/bootstrap5-tags#91]
# Description

I need to add an existing value by input and without select a value in suggestion list.

In fact, i can add a new value (allowNew) but add an existing value is not possible.

Is it correct ?

**Comment by Gaetanbrl** [comment]
An alternative seems to use `onCanAdd` to detect addition value.

**Comment by lekoala** [comment]
@Gaetanbrl does it answer your question?
