### ISSUE TITLE
Accessibility issue in Firefox

### ISSUE THREAD

**Issue by Sitetools** [lekoala/bootstrap5-tags#92]
Love the library, however I have come across an accessibility issue in Firefox.
The input field created doesn't have an aria label in Firefox but does have one on Chrome.
Is this something that can be resolved?

 
![Screenshot from 2023-06-14 13-26-21](https://github.com/lekoala/bootstrap5-tags/assets/8812656/fe468461-174b-402e-8f36-b7d9eb7b39d7)
![Screenshot from 2023-06-14 13-29-15](https://github.com/lekoala/bootstrap5-tags/assets/8812656/10348314-5b2f-403a-a001-9cd435df6a2b)

**Comment by lekoala** [comment]
ok, it seems that firefox is kind of but in terms of support for aria properties
https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaLabel

i have used regular attributes instead
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.24

**Comment by lekoala** [comment]
closing this, let me know if that's not working as expected
