### ISSUE TITLE
Some thoughts on new select functionality (1.6.[01])

### ISSUE THREAD

**Issue by axllent** [lekoala/bootstrap5-tags#93]
Hi @lekoala. I have some feedback regarding one of the new features you've added in 1.6.0 ("make this work more like a select element"). With no disrespect intended, I do not find it very user-friendly or intuitive. It seems you are trying to both achieve the traditional tag select functionality as well as a dropdown, but the result has landed somewhere in between that is not quite either of those two. This makes it (in my opinion) a bit confusing and a difficult to use.

1) I think the dropdown to display all options (on focus) should be opt-in (or at least possible to disable) - to revert back to the original way it worked whereby the dropdown is only shown when a user starts to type something. I am thinking of situations whereby there may be 100 or 200 different available tags. By presenting the full list on focus, the user is inclined to start scrolling rather than searching which can be counter-productive. I think the option for a "full dropdown" (display all options) could still be achieved in this case if the "drop icon" on the right was a button rather than a background image (a bit like "show all available tags").

2) I think the new dropdown should also act more like a traditional dropdown and extend the full width of the virtual select field to prevent jumping around. Currently you have to chase the dropdown when selecting options:
![jump](https://github.com/lekoala/bootstrap5-tags/assets/1463435/3a0d56e8-4514-4396-aae1-e0327c59d7d7)
Github itself has a fairly good example of what I mean when editing topics of a project (sorry, I can't get it to work when recording to show you what I mean).

I'm not sure what your feelings are, or whether this feedback is of any use to you, but hopefully it makes sense? Thanks again for this awesome module!

**Comment by lekoala** [comment]
hi @axllent 

thanks for the feedback ! it's always good to hear what others think

1. yes, you can obviously see the suggestionThreshold to 1 and it should give you what you had before. Currently, the "single select" experience was kind of odd and it was strange to have a dropdown like menu without the drop icon. The idea is this : for live server (where you NEED to type) it defaults to 1 char, otherwise, it's 0. But you are free to change it. I think it's probably what people expect but i may be wrong :-)
Using the drop icon as a button is clearly not what i have in mind, here the goal is to align with how a select element is displayed by bootstrap. but you are free to use addons to open/close the menu.
2. you make a very good point about full width, that should probably be the default, i'll probably publish version 1.7.0 soon that changes that.

**Comment by lekoala** [comment]
@axllent you can have a look at the latest file on master, it should improve things quite a bit :-)

- fullwidth by default
- you can hide the drop icon if you don't like it (showDropIcon)
- fullWidth menu positioning has been improved to follow more closely what bootstrap does (2px offset below input)

**Comment by axllent** [comment]
Hi @lekoala. You're absolutely right, I hadn't considered `suggestionThreshold` which definitely addresses my first point and works exactly as I had intended. 

I've just tried the latest commit and I think this replicates a common dropdown much more accurately (well done), and the ability to set `data-full-width="false"` together with the suggestion threshold works nicely to restore the original functionality. For my use-case (I use this module in [Mailpit](https://github.com/axllent/mailpit)) the "select" field is almost the full width of the page, which just looks strange to have a full width dropdown, so using `data-full-width="false" data-suggestions-threshold="1"` will give me what I was looking for. For projects with narrower multiselects (eg: like your demo) I think the full-width dropdown will work very nicely :+1: 

I think these (unreleased) changes have now the right balance between the two features, and allows enough flexibility to adjust depending on the user-case / preference without confusion. Thanks again! Do you want me to leave this open until you release the next version containing these changes?

**Comment by lekoala** [comment]
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.6.2

released with many other tweaks :-)

thanks again for your feedback. i'm closing the issue, but let me know if you have any other feedback :-)

**Comment by lekoala** [comment]
@axllent by the way, if you want to use this in silverstripe, i've recently made this
https://github.com/lekoala/silverstripe-form-elements

**Comment by axllent** [comment]
@lekoala - that's awesome, I actually noticed (over the weekend) your Silverstripe modules! I'll definitely take a look at those some time in the near future :)
