### ISSUE TITLE
removeAll() does'nt work if additem() was used

### ISSUE THREAD

**Issue by halali** [lekoala/bootstrap5-tags#95]
Hello,

after version 1.6.0 stopped to work addItem function with removeAll function

if i use _add() than removeAll work as before... but if i use addItem removeAll does not make any effect

**Comment by lekoala** [comment]
@halali that's strange. i've just added a test in the demo https://github.com/lekoala/bootstrap5-tags/commit/32114623538de36e18bcbb11b6134e59aae2b7ea and i don't seem to have the issue. i can call addItem then removeAll without worries

can you try with the latest version on master? or provide a codepen that shows the issue?

**Comment by halali** [comment]
ok im also not able to reproduce it on the dome code... so it should be something in my app specifically...

thank you... i will try to digg more, i will let you know

**Comment by lekoala** [comment]
closing this feel free to reopen if you can show a reproduceable issue
