### ISSUE TITLE
Items in OptGroup selected before init are not added as labels

### ISSUE THREAD

**Issue by ofo33** [lekoala/bootstrap5-tags#96]
I try to display labels for items selected in different optGroups.
None are displayed. It seems the the setData(src, true) call exits before finishing the initialization when there is any optgroup.

**Comment by lekoala** [comment]
do you have some sample code that show the issue? setData is fairly new so it's possible i've missed some cases

**Comment by lekoala** [comment]
i have updated the demo let me know if you have any other question it seems to work fine as far as i can tell
https://github.com/lekoala/bootstrap5-tags/commit/f130876a479be64fd08bc3b1908dcb900550cbe3
