### ISSUE TITLE
Is possible to copy and paste multiple tags 

### ISSUE THREAD

**Issue by DanielKimmich** [lekoala/bootstrap5-tags#99]
Hello, congratulations on your library.

I have the following query, is possible to copy and paste multiple tags into another field?

Thank you so much.

**Comment by lekoala** [comment]
@DanielKimmich now it does :-)
https://github.com/lekoala/bootstrap5-tags/commit/2c1b03a7069171c5fe6864e883cc95f9349f5c77

you can give it a try on master, and i'll publish a new release when i got some time to review this better

**Comment by DanielKimmich** [comment]
Thanks for the quick reply.

I didn't understand how to use it, I copied the new code to my project.
I try to copy and paste but it does it as a single tag

![image](https://github.com/lekoala/bootstrap5-tags/assets/44840413/26d8c069-eb51-4d50-867e-7b2b6d52a12d)

copiar a:
![image](https://github.com/lekoala/bootstrap5-tags/assets/44840413/09ed5a26-2cc1-4be0-822f-9583e1681d5c)

**Comment by lekoala** [comment]
are you using the master branch?

**Comment by DanielKimmich** [comment]
Hello, my separator is default <enter>

In my select I have:

```
<select 
    class="{!!$clase!!}" 
    id="{{ $name }}" 
    name="{{ $name.'[]' }}" 
    multiple 
    data-full-width="true" 
    data-allow-clear="true" 
    data-allow-new="{!!$new!!}"
    data-badge-style="{!!$badge!!}" 
    data-suggestions-threshold="0"
    data-selected="{!!$selected!!}"
    >
```
Yes i have this script "tags.js"

```
<script type="module">
        import Tags from "{{ asset('packages/bootstrap5-tags/tags.js') }}"
        Tags.init("#{!!$name!!}");
```

![image](https://github.com/lekoala/bootstrap5-tags/assets/44840413/91171c08-a332-47be-b515-a5daf48bb0b3)

kind regards
D.K.

**Comment by lekoala** [comment]
try with data-separator=" |,|  "

**Comment by DanielKimmich** [comment]
Excellent, adding that line in my code, it worked.
Thank you very much for your predisposition.

**Comment by lekoala** [comment]
you are welcome
published here https://github.com/lekoala/bootstrap5-tags/releases/tag/1.6.9
